### ISSUE TITLE
Output dir config does not allow relative directory outside of source files

### ISSUE THREAD

**Issue by joshrcook** [Cecilapp/Cecil#1023]
It appears that the config does not allow relative output directories that are outside of the Cecil directory.

## To reproduce

1. Put cecil inside a project subdirectory (ex. `site/content`, `site/layouts`, `site/static`), and install `cecil.phar` in the root
2. Add the following to the `config.yml`: 
```
output: 
  dir: ../dist
```
3. Run `php cecil.phar build -- site`.  
Site builds to `site/_site`.
4. Run `php cecil.phar build --output=../dist -- site`.  
Site builds to `dist`.

## Expected behavior

I would expect both commands to build to the root `dist` directory.

**Comment by Narno** [comment]
Hello @joshrcook, what do you mean by "Put cecil inside a project subdirectory, and install `cecil.phar` in the root" ?

I'm not able to reproduce your case.
