### ISSUE TITLE
HTML form example

### ISSUE THREAD

**Issue by rettal** [Cecilapp/Cecil#1026]
## Is your feature request related to a problem? Please describe

Request for example of creating a page with a HTML form.

## Describe the solution you'd like

An example of how to create a contact page for example.

## Describe alternatives you've considered

A Netlify form example would be good but since that is just an HTML form with an attribute, an example of the best way to create a simple page with a contact form, the docs do not seem to mention anything about HTML forms? Is this use case not covered?

## Additional context

Thanks for any help.

**Comment by Narno** [comment]
Hello @rettal, you can find some tutorials about serverless contact form, like this one: https://www.smashingmagazine.com/2018/05/building-serverless-contact-form-static-website/.

About Netlify Forms, it's very easy and you can find a simple example here: https://github.com/Cecilapp/theme-comingsoon/blob/main/layouts/partials/subscribe.html.twig.
