### ISSUE TITLE
Circular pagination possible without hard coding prev/next page id?

### ISSUE THREAD

**Issue by haraldgroven** [Cecilapp/Cecil#1029]
I run a Cecil powered image gallery where each page has a link for _< previous page_ and _next page >_.  
If a user clicks through the gallery using the _next page >_ links consecutive times, the gallery should not end with the last page but link the last page to the first page so that the previous/next creates a circular link chain. 

1. clicking the _next page >_ link: 
Page_A -> Page_B -> Page_C -> Page_D (last page) -> Page_A -> Page_B  etc. 
2. and by _< previous page_ link 
Page_A <- Page_D <- Page_C <- Page_B <- Page_A <- Page_D etc. 

- Is this possible to achieve by using twig templates and `page.pagination`? 
- Can such circular pagination be created for pages tagged with the same taxonomy term?
- Could the documentation or examples be extended with an example using circular pagination?

**Comment by Narno** [comment]
Hello @haraldgroven, could you try this new feature of v5.44: https://cecil.app/documentation/content/#circular?
