### ISSUE TITLE
Delete/disable list page in section

### ISSUE THREAD

**Issue by sooluh** [Cecilapp/Cecil#1110]
Hello there, can I delete or disable the listing page in one of the sections?

**Edit:**

Sorry, I edited with a little explanation 😅 

I'm trying to create a section with the name `major` (just as an example). After rendering, I get an index.html file in the `major` directory, it contains a list of pages created in the `major` section.

My question is, is it possible if I disable or remove the `index.html` file in the rendering process? maybe in the `config.yml` file or is this feature not yet available?

Thank you 😁

**Comment by Narno** [comment]
Hello @sooluh, do you mean do not published the index/list page of a section? just the child pages?

In this case your users should know the exact path to the child pages to access it: is it OK ?

**Comment by sooluh** [comment]
Oh my bad, I'm not careful in reading the documentation. Thank you very much.
