### ISSUE TITLE
Garbage pagination

### ISSUE THREAD

**Issue by sooluh** [Cecilapp/Cecil#1111]
The `page` directory is rendered useless in the root directory (literally in the `_site` directory) in fact I think this is garbage.

Maybe in my opinion, pagination is made per section only and flexible, meaning that it can be enabled and disabled.

Thank you 😄

**Comment by Narno** [comment]
Hello @sooluh, pagination is enabled by default but you can disable it:

1. globally: https://cecil.app/documentation/configuration/#disable-pagination
2. by section: https://cecil.app/documentation/content/#pagination

And more, if you want enable pagination for all sections except home page (home page is a "meta" section that list all pages), just create a `index.md` file at the root with the following front matter:

```yaml
---
pagination:
  enabled: false
---
```

Does this help you?

**Comment by sooluh** [comment]
Hehe yeah that's what I meant, thanks for helping 😅
