### ISSUE TITLE
Get section variable

### ISSUE THREAD

**Issue by sooluh** [Cecilapp/Cecil#1115]
Hello there, can I get the value of a variable that I have declared in the front matter in a certain section of the page?

**Let's say**, I create a file `sooluh.md` in the "author" section, then I declare variables such as name, website, email, etc., and then I want to call one of the variables (eg email) from the file `sooluh.md` that, is it possible?

**Comment by Narno** [comment]
Hello @sooluh, this is not a "native" feature of Cecil but you can do that with the experimental feature _Dynamic content_: https://cecil.app/documentation/content/#dynamic-content.

**Comment by sooluh** [comment]
Wow thanks, I can try it.
