### ISSUE TITLE
Count total pages in section

### ISSUE THREAD

**Issue by sooluh** [Cecilapp/Cecil#1116]
Hello, I've read the documentation many times, maybe I'm not very thorough, but can I count the total pages in a specific section and display it in the layout?

Thanks for any help.

**Comment by sooluh** [comment]
Hello again there, sorry to bother hehe.<br />I just explored the twig documentation page. My crooked logic thought and I found the way below. If there's still a shorter way, please keep telling me 😄

For example, the section I'm going to count is the "majors" section, I'm using a filter function, like this.
```twig
{{ site.pages.all|filter(s => s.section == 'majors')|length }}
```

Maybe the filter function that I use here also works if you want to display a list of pages that are in a section to a certain layout.
```twig
{% for major in site.pages.all|filter(s => s.section == 'majors') %}
    {# ... #}
{% endfor %}
```

**Comment by Narno** [comment]
> If there's still a shorter way, please keep telling me

Nope, you use the best way! 👍
