### ISSUE TITLE
Import remote JSON data

### ISSUE THREAD

**Issue by sooluh** [Cecilapp/Cecil#1153]
### Related to a problem?

It doesn't seem like a big deal, but maybe it would be better if this was realized? I just want to fetch JSON data from outside (remotely), and it looks like Cecil doesn't exist yet?
#cmiiw

### Describe the solution you'd like

I found this plugin on Jekyll, and that's pretty much what I wanted😀
[brockfanning/jekyll-get-json](https://github.com/brockfanning/jekyll-get-json)

### Additional context

Thanks for all the help😄

**Comment by Narno** [comment]
Hello @sooluh, it could be possible to access to a remote JSON file with the [`asset()`](https://cecil.app/documentation/templates/#asset) function, then decode it.

Something like that:

```twig
{% set superheroes = asset('https://mdn.github.io/learning-area/javascript/oojs/json/superheroes.json').content|json_decode %}
```

**Comment by Narno** [comment]
I made a quick test here: https://json--arnaudligny.netlify.app/json.

**Comment by sooluh** [comment]
oh hi, I just tried it and it worked. I didn't think the `asset()` function could be used for JSON, thanks again for the help😅
