### ISSUE TITLE
Deprecated on PHP 8.1

### ISSUE THREAD

**Issue by ensimo** [Cecilapp/Cecil#1256]
### Describe the bug

```text
Deprecated: Return type of _HumbugBox87c495005ea2\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///cecil.phar/.box/src/RequirementCollection.php on line 15

Deprecated: Return type of _HumbugBox87c495005ea2\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///cecil.phar/.box/src/RequirementCollection.php on line 19
```

### To reproduce

- PHP 8.1
- Cecil 5.79.7

```bash
docker run -it --rm php:8.1-cli bash -c "curl -LO https://cecil.app/cecil.phar && chmod +x cecil.phar && ./cecil.phar new:site"
```

Same on macOS with PHP 8.1.1 (cli) (built: Dec 17 2021 22:38:05) (NTS)

### Expected behavior

No Deprecated messages

### Version

5.79.7

**Comment by ArnaudLigny** [comment]
Hello @ensimo, thanks for your report.

I'm working on a new release to support PHP 8.x, but this is a problem with the way I build PHAR: box-project/box#562. The PR to fix it (box-project/box#578) is already in progress.

I'm waiting :-)

**Comment by ArnaudLigny** [comment]
Work in progress (finally) : the last beta ([6.0.0-beta.6](https://github.com/Cecilapp/Cecil/releases/tag/6.0.0-beta.6)) is now working with PHP 8.1 (and PHP 8.2).

While waiting for the stable release (certainly tomorrow), you can test the preview via:

```bash
cecil self-update --preview
```

**Comment by ArnaudLigny** [comment]
Hello @ensimo, Cecil finally support PHP 8.1+ with the [last release](https://cecil.app/news/2022/08/04/cecil-6.0.0-released/) 🥳 

```bash
cecil self-update
```
