### ISSUE TITLE
Add config option to disable fetching image assets from Page content

### ISSUE THREAD

**Issue by zemian** [Cecilapp/Cecil#1338]
### Related to a problem?

See this Discussion for details of problem: https://github.com/Cecilapp/Cecil/discussions/1337

### Describe the solution you'd like

When building a site, we should have an option to generate content without Cecil pulling images from page and store it in `_site/assets` folder. This only only prevent unnecessary assets to be generated, but in cases where user are behind proxy server, it could hang their Cecil build process. 

### Describe alternatives you've considered

N/A

**Comment by ArnaudLigny** [comment]
WIP: #1342

**Comment by ArnaudLigny** [comment]
Done: https://cecil.app/documentation/configuration#body (version 5.90.0).
