### ISSUE TITLE
Static dotfiles ignored

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1419]
### Describe the bug

Files starting with dots (e.g. `.htaccess`) do not get copied from `static` when building. This is because Symfony's Finder excludes them by default, but I can't think of a good reason to exclude them (and, as with `.htaccess`, several good reasons *to* include them!)

### To reproduce

1. Create `static/.htaccess`
2. Run `cecil.phar build`
3. Stare at the lack of `_site/.htaccess`

### Expected behavior

`.htaccess` (and other dotfiles) should be copied from static.

### Version

5.104.1

### Operating System

Ubuntu 20.04

**Comment by ArnaudLigny** [comment]
Hello @ahnlak, thanks for your report.

This should be fixed with PR #1420 and released with the last version (5.104.2).
