### ISSUE TITLE
PHP required intl extension installed

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1474]
### Describe the bug

Since https://github.com/Cecilapp/Cecil/pull/1463, running without `php-intl` installed will generate an error on build :+1: 

```
[ERROR] The Symfony\Component\Intl\Locale\Locale::setDefault() is not implemented. Please install the "intl" extension for full localization capabilities.                                         
```

This doesn't seem to be installed by default with PHP7.4 (Ubuntu 20.04), so probably needs mentioning in the system requirements.

(it's also complicated by the fact that that the error message doesn't make it clear if it's talking about a PHP extension or a Symfony one)

### Expected behavior

Ideally, a clearer error message and guidance in the quick start guide.

### Version

7.5.0

### Operating System

Ubuntu 20.04

**Comment by ArnaudLigny** [comment]
Hello @ahnlak,

Thanks for the repport. Could you give me more details about the context?

In fact the Symfony/Intl component is used by Twig/Extra extension et more precisely by the `format_date` filter.

So the problem is that the Symfony/Intl layer works only with the "en" locale... In the case of another locale, PHP ext-intl is required (see https://php.net/intl.setup).

**Comment by ahnlak** [comment]
Sure; clean Ubuntu 20.04 install, and `apt install php`, which installs PHP 7.4.3.

Clean copy of Cecil (7.5.0), as per the quickstart.

Running `cecil.phar new:site` will complain about a couple of PHP packages missing (`gd`, `simplexml`), but runs fine once those are installed.

Running `cecil.phar build` will fail with the error mentioned above (I'm guessing the default new site stuff includes some date formatting?) - installing intl (`apt install php-intl`) resolves it and allows the build to complete.

It probably only came up because I never happened to need `intl` installed on my dev box; until I tested on a clean Ubuntu, I hadn't realised that other packages are explicitly checked for (`gd` et al) so perhaps the `intl` requirement can be added there?

**Comment by ArnaudLigny** [comment]
OK, I see what's happene: the Intl extension is only required if you need to format a date (`format_date` filter) with a locale different from "en".
So, basically, I tested if the class `\Locale` was available (that mean Intl extension is loaded) but... Symfony/Intl implement this class, but this class is not really umplemented 🙃

**Comment by ArnaudLigny** [comment]
@ahnlak, could you try the last release please (7.5.2, `php cecil.phar self-update`) ?

**Comment by Kpjas** [comment]
> `php cecil.phar self-update`

Again works for me! :-) php 8.1.10

**Comment by ahnlak** [comment]
Yup, 7.5.2 fixes it - super speedy as always!

**Comment by ArnaudLigny** [comment]
Great! :-)
