### ISSUE TITLE
Prevent build errors due to incompatible cache content after update

### ISSUE THREAD

**Issue by hype09** [Cecilapp/Cecil#1501]
### Related to a problem?

Yesterday I updated Cecil from version `7.1.2` to the latest `7.11.1` and saw my build fail with the following error message:

```
Building website...

 [ERROR] Template "/Users/paik/Projects/cecil/resources/layouts/partials/metatags.html.twig:114" (page: another-page):
         Neither the property "missing" nor one of the methods "missing()", "getmissing()"/"ismissing()"/"hasmissing()"
         or "__call()" exist and have public access in class "Cecil\Assets\Asset".
```

I believe this to have been indirectly caused by the changes in #1490.

The older version of Cecil populated the cache with asset data that has no `'missing'` key. The newer Cecil version reads from the cache, expecting the key to exist, causing the error.

A simple deletion has fixed the problem for me, but I spent some time chasing that problem down.

### Describe the solution you'd like

Adding the current Cecil version to cache keys could be a simple and pragmatic solution to this kind of problem. Cache entries would be isolated between version, preventing any such incompatibilities.

I have not looked into the Cecil code base too deeply, but this change could potentially be implemented inside the `\Cecil\Assets\Cache` class.

### Additional context

I would gladly attempt to provide an implementation if you believe this to be a good solution. Also, I'd be keen to hear of any other ideas you might have.

**Comment by ArnaudLigny** [comment]
Hello @hype09 and thanks a lot for the report.

> Adding the current Cecil version to cache keys could be a simple and pragmatic solution to this kind of problem. Cache entries would be isolated between version, preventing any such incompatibilities.

I love this idea: simple et effective :+1:

**Comment by ArnaudLigny** [comment]
Done here: 207428c7dab8f13507f4fc54f0e6c16e033b7776.

**Comment by ArnaudLigny** [comment]
And released: https://github.com/Cecilapp/Cecil/releases/tag/7.15.4
