### ISSUE TITLE
_term_ generic template override

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1669]
### Related to a problem?

Generated taxonomy lists will only use user-provided layouts of the form `taxonomy/<term>.<format>.twig` before falling back to the defaults. This requires individual layouts for all possible custom taxonomy terms, which is obviously less than ideal.

### Describe the solution you'd like

Add another option of the form `taxonomy/<singular>.<format>.twig` to be a generic handler for a taxonomy list layout; this effectively is a local version of `_default/term.<format>.twig`

### Additional context

To give an example; I have a taxonomy of `years`, and posts tagged with a variety of years. 

I want to produce customised layouts to list posts by year (`mydomain.com/years/2023`) rather than the rather generic _default layouts, but that would require me to create `layouts/taxonomy/2023.html.twig` as well as `layouts/taxonomy/2022.html.twig` for every year I use.

Much nicer would be to have a single `layouts/taxonomy/year.html.twig` to be used for all years.

**Comment by ArnaudLigny** [comment]
Hello @ahnlak, thanks a lot for your detailed issue.

I understand your need and... yeah it so obvious that I'm surprised I haven't come across this problem before :-P

I'm trying to fix that.

**Comment by ArnaudLigny** [comment]
Feature introduced in the last version, see https://cecil.app/documentation/templates/#type-term

**Comment by ArnaudLigny** [comment]
Demo on my website:

- config: https://github.com/ArnaudLigny/arnaudligny.fr/blob/master/config.yml#L12
- template: https://github.com/ArnaudLigny/arnaudligny.fr/blob/master/layouts/taxonomy/year.html.twig
- years/2023: https://arnaudligny.fr/years/2023/

**Comment by ahnlak** [comment]
Super fast response as always, works perfectly!
