### ISSUE TITLE
Provide access to paginator path setting

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1694]
### Describe the solution you'd like

There is currently no way (that I can find!) to access the custom path set in a section's `index.md` front matter:

```
pagination:
  max: 10
  path: "somethingelse"
```

I'm building my own custom `partials/paginator.html.twig` but I can't see any way to find out the pagination path in use - `path.pagination` gets automagically directed to the pagination object, which doesn't include any path information.

(There's also no access to `max` directly, although you can derive that from `totalpages` and `count`)

### Describe alternatives you've considered

At the moment, I will use a common site-wide path (which I can access through `site.pagination.path`), which is probably better from a UI perspective anyway - but if there is a way to provide a custom path per index, it would make sense to be able to access it.

**Comment by ArnaudLigny** [comment]
Hello @ahnlak, I trying to understand what you want to do, but I not able: could you provide a simple example of your goal?

Maybe this is a misunderstanding about the definition of the `path` variable of `pagination`, does not define the full path to the pagination page, but only its "sub-path".

For example for `baseurl/section/page/2` it is only a question of replacing "page" and not "section/page".

With:
```
pagination:
  path: "somethingelse"
```

`baseurl/section/page/2` become `baseurl/section/somethingelse/2`

**Comment by ahnlak** [comment]
Apologies; I probably didn't explain myself well!

For my custom pagination, I want to provide "page number" buttons to take the user directly to (for example) page 3 of the pagination, but to do that I need to know that 'sub-path' too.

That would be `baseurl/section/somethingelse/2`, but there is no way I can see to know the value of `somethingelse` from the pagination object - only the sitewide setting.

Does that make any better sense? If not I'll try to give a more comprehensive example after dinner :-)

**Comment by ArnaudLigny** [comment]
Haaaa, I see now! :-)

OK, it's definitvely a feature I should introduice to the navigator object: provide a detailled array of paginated pages.

However you can inspire from another site built with Cecil (https://libimobiledevice.org/news/) who use a simple trick to do what you want (be carreful it's an old version of Cecil):
https://github.com/libimobiledevice/libimobiledevice.org/blob/master/layouts/partials/pagination.html.twig

**Comment by ahnlak** [comment]
Ha! I *very* nearly used that trick, but then I decided it probably made more sense to just use a single, site-wide sub-path definition.

But once the thought was in my head, I thought I'd add it to your to-do list :wink:

**Comment by ArnaudLigny** [comment]
@ahnlak #1696
