### ISSUE TITLE
Provide raw access to all page front matter

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1699]
### Related to a problem?

As I'm in the process of porting an existing site into Cecil, I've stumbled into problems with publish and update dates. Specifically, that if they are not provided, they are derived from filesystem dates and *there is no way* to determine if a given page's `page.updated` date is user-provided or automatically worked out.

This is a problem if, for example, you are moving / editing files containing old content - or if you want to know if a page has ever been updated (because even when not defining an `updated` field, a value is still provided)

### Describe the solution you'd like

It would be useful to be able to access *all* front matter variables (ideally in their raw form), possibly in a dedicated `page.frontmatter` object, so that templates can see all the page data and decide whether to use the raw data or the system calculated data.

That way, if an updated date is not provided in the frontmatter,  `page.updated` could remain set to the file modification date and  `page.frontmatter.updated` could be tested to detemine if there had been a content update.

This applies outside of `date` and `updated` - my initial thought was to add extra data to `scheduled` (since that isn't derived from file date information), but there is no `page.schedule` exposed either.

### Describe alternatives you've considered

For the moment, I just ensure that `updated` is set by default to match `date`, and use that equality to determine if a page is considered to be updated, but that feels like an untidy solution.

**Comment by ArnaudLigny** [comment]
Hello @ahnlak, quick answer: there is a no documented method to retrieve frontmatter's variables:

```yaml
page.fmvariables
```

**Comment by ahnlak** [comment]
Ahh, that is absolutely perfect!

(I did try looking through the code but managed to miss that - got distracted by trying to work out how index pages get their dates generated!)

Thanks as always.
