### ISSUE TITLE
exclude causes blank page.section

### ISSUE THREAD

**Issue by ahnlak** [Cecilapp/Cecil#1703]
### Describe the bug

If I set every page in a section to `exclude: true` (or, every page but `index.md`), then `page.section` is empty for *all pages within that section*

### To reproduce

1. Create a section : `pages/blog`
2. Create pages in that section : `pages/blog/index.md` as normal, `pages/blog/page1.md` with `exclude: true` set.
3. Pages _correctly_ absent from `site.pages.showable`
4. `page.section` _incorrectly_ appears empty when rendering both pages listed in 2.

### Expected behavior

I would expect the pages to be (correctly) excluded from lists (such as `site.pages.showable`), but with `page.section` correctly set to `blog`.

### Version

7.39.3

### Operating System

Linux Ubuntu 20.04

**Comment by ArnaudLigny** [comment]
Hello @ahnlak, for a reason I don't remember why (...) the `section` variable is reseted for not published and excluded pages: https://github.com/Cecilapp/Cecil/blob/master/src/Generator/Section.php#L39-L41

I will remove this behavior locally and doing some tests.

**Comment by ahnlak** [comment]
I'm aware that I'm probably using Cecil in strange ways, and while I can certainly work around it I figured it was worth raising just in case it was unintended behaviour.

I promise to stop raising issues soon :grin:

**Comment by ArnaudLigny** [comment]
You are right and I think it's a good point. So, I have removed this apparently old and useless code: now the section of an excluded page is preserved.
