### ISSUE TITLE
Responsible disclosure policy

### ISSUE THREAD

**Issue by psmoros** [Cecilapp/Cecil#1780]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@ouuan) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by ArnaudLigny** [comment]
Hello @psmoros, you should be able to create a security report in the following section of the repository: https://github.com/Cecilapp/Cecil/security

**Comment by ouuan** [comment]
> Hello @psmoros, you should be able to create a security report in the following section of the repository: [Cecilapp/Cecil/security](https://github.com/Cecilapp/Cecil/security)

I'm using https://huntr.dev/ and have already written the reports there. They want your email in a `SECURITY.md`.

The links are https://huntr.dev/bounties/d2a9ec4d-1b4b-470b-87da-ec069f5925ae/ and https://huntr.dev/bounties/cdd995b2-c983-428b-a73a-827b61b7c06b/ . They are not publicly visible now. I'm not sure if the maintainer can view them before being contacted by huntr admins.

**Comment by ArnaudLigny** [comment]
Hello @ouuan the SECURITY.md file is now up to date: https://github.com/Cecilapp/Cecil/blob/master/SECURITY.md

**Comment by ouuan** [comment]
Hello @ArnaudLigny, have you received the email?

![We have contacted a member of the[ cecilapp/cecil](https://github.com/cecilapp/cecil) team and are waiting to hear back](https://github.com/Cecilapp/Cecil/assets/30581822/8b5b5213-1c10-44e2-a3dd-3f9a8a866d91)

**Comment by ArnaudLigny** [comment]
@all-contributors please add @ouuan for security.
