### ISSUE TITLE
Resume theme support

### ISSUE THREAD

**Issue by peter279k** [Cecilapp/Cecil#1802]
### Related to a problem?

As title, it seems that themes are only available Blog and I think it should support the resume themes, too.

### Describe the solution you'd like

I think we can consider including these resume themes:

- https://jekyllthemes.dev/a-modern-static-resume-template-and-theme
- https://jekyllthemes.dev/a-markdown-based-resume-generator
- https://jekyllthemes.dev/a-simple-jekyll-github-pages-powered-resume-template

**Comment by ArnaudLigny** [comment]
Hello @peter279k, good idea, work in progress: https://github.com/Cecilapp/theme-resume.

**Comment by peter279k** [comment]
Thanks! It's great for me and going to close this issue now :).
