### ISSUE TITLE
Support fediverse:creator meta tag and Mastodon website verification

### ISSUE THREAD

**Issue by maxalmonte14** [Cecilapp/Cecil#2074]
### Related to a problem?

Hi Arnaud, allow me to explain myself.

I'm referring to two things here, first Mastodon's website verification, which Mastodon defines as:

"...All you need is a personal website that people recognize you by. When you link to this website from your profile, we will check that the website links back to your profile and show a visual indicator on it."

For this we would need to add an anchor tag to our website like the following one, but a `link` tag works perfectly fine too.

```html
<a rel="me" href="<domain>/<username>">Mastodon</a>
```

Or

```html
<link rel="me" href="<domain>/<username>"/>
```

This is basically a way to get a check mark next to your website domain when you add it to Mastodon, thus confirming you own it.

Second it's the [fediverse author tag](https://blog.joinmastodon.org/2024/07/highlighting-journalism-on-mastodon/), which allows web publications to be linked to a fediverse user when shared on Mastodon, this tag looks as follows:

```html
<meta name="fediverse:creator" content="<@username>">
```

Now, there's a bit of a discrepancy between these two features, the first one is supposed to be Mastodon exclusive while the second one, although introduced by Mastodon could in theory identify any user across the fediverse as the author of a web publication, so if they should be grouped under the same category is up for debate.

I add examples of valid tags for completion's sake.

```html
<a rel="me" href="https://indiehackers.social/@maxalmonte14">Mastodon</a>
<link rel="me" href="https://indiehackers.social/@maxalmonte14"/>
<meta name="fediverse:creator" content="@maxalmonte14@indiehackers.social">
```

### Describe the solution you'd like

By adding these tags by default in `layouts/partials/metatags.html.twig` users with the right entries in `cecil.yml` (or any particular page) could benefit of Mastodon's website verification and getting their username linked to their articles when shared to the fediverse (after they've done the proper configuration on Mastodon of course).

The documentation should be updated accordingly.

### Describe alternatives you've considered

This can always be implemented in user-land after extracting Cecil's default templates of course.

### Additional context

I made a working implementation [here](https://github.com/maxalmonte14/Cecil/commit/ff18f9a7193efbbafc2023d04f3053cd0fc8bbd3) based on what it's already in place for Facebook and Twitter, we could discuss about how optimal it is and what changes are needed in case adding this makes sense.

**Comment by ArnaudLigny** [comment]
Hello @maxalmonte14, I loved the feature, so I done it :-)

https://github.com/Cecilapp/Cecil/pull/2075

**Comment by maxalmonte14** [comment]
> Hello @maxalmonte14, I loved the feature, so I done it :-)
> 
> ➡️ #2075

Sweet! Thanks for the work you do @ArnaudLigny.

> And please note that Cecil already support `rel=me` links with the following config syntax :
> 
> ```yaml
> social:
>   <name>:
>     url: <URL>
> ```
> 
> https://github.com/Cecilapp/Cecil/blob/c1d9b18e9e5d4f9eae1c2c22adf00ed62470ebce/resources/layouts/partials/metatags.html.twig#L178C1-L181C15

Had a real "RTFM" moment there, I apologize, was tinkering late last night and did not occur to me to check for an existing `rel="me"` 😅

**Comment by maxalmonte14** [comment]
Realizing this was never closed, closing it so it doesn't pollute the repo.
