### ISSUE TITLE
Template changes during watch

### ISSUE THREAD

**Issue by maxperei** [Cecilapp/Cecil#321]
hi everyone, 
i'm really enjoying the cecil + netlifycms stack right now but i feel something is messing around
ie. when i `cecil serve` it livereloads every assets except templates (twig files) and i have to `cecil build` again to see applied changes..

i wanted to know if i can find a way to fix this ?

**Comment by Narno** [comment]
Hello Maxime,

Unfortunately it's a "known bug": for a reason that I - still - don't know it seems that the Twig cache (the template engine) is persistent between each build (in serve mode).

I have already tested different approaches in the past to solve this problem, without success... :-/

If I have the time and courage during the next weeks I will try again.

Thanks for your feedback.

**Comment by maxperei** [comment]
hey arnaud,
i'll take a half-hearted look on my side too, btw thanks for your answer

**Comment by Narno** [comment]
Hello @maxperei, a temporary workaraound could be to use `--no-watch` (`-nw`) option to disable the watcher.
In this case, you have just to stop (`ctrl+c`) the server and (re)run it (`cecil serve -nw`) after a template modification.

**Comment by maxperei** [comment]
hello @Narno, 
i know it's been a long long time but i think i figured out what's going on about this
first, sure this does not relate to twig directly, but something more associated with the `buildCommand->run($buildInput, $output)` method inside `Serve.php` which is not re-building templates properly (maybe due to a fail of the `Process` cache reconstruction, idk)
___
btw, if you force a full regeneration by putting a `Process::fromShellCommandline('vendor/bin/cecil build')->run()` instead of the previously quoted build command this actually solves it.. like if you re-run ina separate process

anyway, it's really dirty, and a pull request deserves something better
see u,

**Comment by Narno** [comment]
Hello @maxperei,

Interesting approach: I will try to take the time to investigate in this direction.

Thank you! 🤗
