### ISSUE TITLE
Json to contents

### ISSUE THREAD

**Issue by Lowell130** [Cecilapp/Cecil#679]
Hello it's possible use json file (with data) to generate contents, and how?
thanks for great app

**Comment by Narno** [comment]
Hello @Lowell130, you can't generate pages directly from a JSON file, but you can load data from a JSON, YAML, XML or CSV file in a template.

For example data from `data/file.json` could be printed with:
```twig
{% for data in site.data.file %}
  {{ data.example }}
{% endfor %}
```

Docs:
- https://cecil.app/documentation/content/#file-system-tree
- https://cecil.app/documentation/templates/#site
