### ISSUE TITLE
Remove Section From URL

### ISSUE THREAD

**Issue by BayuAngora** [Cecilapp/Cecil#813]
How to change URL from domain.tld/(section)/new-post/ to domain.tld/new-post/ without any section include on path URL?

**Comment by BayuAngora** [comment]
> > But I have uploaded more than hundreds. I won't change those uploaded files one by one. Can I change it from config.yml instead?
> 
> Hum, I understand but there is no config option to manage path of sections globaly.
> It could be a good feature for a future release, something like that:
> 
> ```yaml
> sections:
>   - name: mysection
>     path: %slug%
> ```
> 
> (`%slug%` would be replaced by the slug of the page in the section `mysection`)

That's good feature.

**Comment by Narno** [comment]
Hello @BayuAngora,

I have deployed a new release ([5.30.0](https://github.com/Cecilapp/Cecil/releases/tag/5.30.0)), with an experimental feature, if you want to try.

Documentation: https://cecil.app/documentation/configuration/#paths.

Example:

```yml
paths:
  - section: Blog
    path: :slug
```

**Comment by BayuAngora** [comment]
> Hello @BayuAngora,
> 
> I have published a new release ([5.30.0](https://github.com/Cecilapp/Cecil/releases/tag/5.30.0)), with an experimental feature, if you want to try.
> 
> Documentation: https://cecil.app/documentation/configuration/#paths.
> 
> Example:
> 
> ```yaml
> paths:
>   - section: Blog
>     path: :slug
> ```

Thanks. New feature is works. I can visit every single page. By the way, I have a question about list.html.twig 

On my Hugo ```layouts/_default/list.html``` I use this code to show my list -> 
```
{{ range (.Paginate (.Pages).Reverse).Pages }}
<article class="list">
<a href="{{ .Permalink }}">
<div class="list-header">
<h2>{{ .Title }}</h2>
</div>
<div class="list-content">
<h3>
{{ .Summary | truncate 80 }}
</h3>
<div class="read-more">➜</div>
</div>
</a>
</article>
{{ end }}
```
The result is like this -> https://angora-hugo.onrender.com 

How to show that result on Cecil ```layouts/_default/list.html.twig```? 
https://angora-cecil.onrender.com

**Comment by Narno** [comment]
:+1:

> How to show that result on Cecil?

There is differents way to achieve this goal: could you share your repository to facilitate our exchanges?

**Comment by BayuAngora** [comment]
> > How to show that result on Cecil?
> 
> There is differents way to achieve this goal: could you share your repository to facilitate our exchanges?

Sure. You can fork it here -> 
https://github.com/BayuAngora/cecil-demo
