### ISSUE TITLE
I have a question about list.html.twig

### ISSUE THREAD

**Issue by Narno** [Cecilapp/Cecil#816]
_Originally posted by @BayuAngora in https://github.com/Cecilapp/Cecil/issues/813#issuecomment-637889992_

Thanks. New feature is works. I can visit every single page. By the way, I have a question about list.html.twig 

On my Hugo `layouts/_default/list.html` I use this code to show my list -> 
```html
{{ range (.Paginate (.Pages).Reverse).Pages }}
<article class="list">
	<a href="{{ .Permalink }}">
		<div class="list-header">
			<h2>{{ .Title }}</h2>
		</div>
		<div class="list-content">
			<h3>{{ .Summary | truncate 80 }}</h3>
			<div class="read-more">➜</div>
		</div>
	</a>
</article>
{{ end }}
```
The result is like this -> https://angora-hugo.onrender.com/blog/

How to show that result on Cecil `layouts/_default/list.html.twig`? 
https://angora-cecil.onrender.com/blog/

**Comment by Narno** [comment]
Hello @BayuAngora, I forked your repo and made some changes: https://github.com/Narno/cecil-demo.

- https://github.com/Narno/cecil-demo/blob/master/layouts/_default/section.html.twig
- https://github.com/Narno/cecil-demo/blob/master/layouts/section/blog.html.twig

**Comment by BayuAngora** [comment]
> Hello @BayuAngora, I forked your repo and made some changes: https://github.com/Narno/cecil-demo.
> 
> * https://github.com/Narno/cecil-demo/blob/master/layouts/_default/section.html.twig
> * https://github.com/Narno/cecil-demo/blob/master/layouts/section/blog.html.twig

Thanks, Narno. It works ->
https://angora-cecil.onrender.com 

Also I use this pagination code to make it works on list page and post page. 
```
<div class="pagination">
<a class="prev" href="{% if page.pagination.links.prev is defined %}{{ url(site.pages[page.pagination.links.prev]) }}{% elseif page.prev is defined %}{{ url(page.prev.path) }}{% endif %}">« Prev</a>
<a class="next" href="{% if page.pagination.links.next is defined %}{{ url(site.pages[page.pagination.links.next]) }}{% elseif page.next is defined %}{{ url(page.next.path) }}{% endif %}">Next »</a>
</div>
```
