### ISSUE TITLE
Tags are not managed.

### ISSUE THREAD

**Issue by thomascenni** [Cecilapp/Cecil#836]
Following the Quick Start documentation, create a new post and add a tag to it as explained here: [https://cecil.app/documentation/content/#front-matter](https://cecil.app/documentation/content/#front-matter)

**To Reproduce**
```
macbook:Desktop thomas$ ./cecil.phar new:site cecil-test
Creating a new website...
Done!
macbook:Desktop thomas$ cd cecil-test/
macbook:cecil-test thomas$ ls
config.yml	content		layouts		static
macbook:cecil-test thomas$ ../cecil.phar new:page blog/my-first-post.md
File "content/blog/my-first-post.md" created.
```
**Then just add some tags to the post**.

```
cat content/blog/my-first-post.md
---
title: 'my-first-post'
date: '2020-06-21'
draft: true
tags: [tag 1, tag 2]
---
```
Serve the application with:

`../cecil.phar serve --drafts`

And you get this error:

[ERROR] Template "cecil:_default/list.html.twig" line 19 (for page
         "tags/tag-1"): Neither the property "all" nor one of the methods
         "all()", "getall()"/"isall()"/"hasall()" or "__call()" exist and have
         public access in class "Cecil\Collection\Taxonomy\Term".

![Screen Shot 2020-06-21 at 15 13 51](https://user-images.githubusercontent.com/33039107/85231954-fa791f00-b3d1-11ea-9046-74db2a1f3a5e.png)

**Comment by Narno** [comment]
Hello @thomascenni , I thinks I have identified teh source of your probleme: could you try with the last version (5.31.4)?

Thanks a lot.

**Comment by thomascenni** [comment]
Yes, I tested and it has been fixed.
When I build the website with the command:

`cecil.phar build`

I can see the generated tags.
But when I serve the pages with:

`cecil.phar serve`

I get a "This page isn’t working
localhost sent an invalid response.
ERR_INVALID_HTTP_RESPONSE"
when trying to access for example http://localhost:8000/tags/tag-1.
Thanks for your quick response.

**Comment by Narno** [comment]
Hum... Have you got a public repository where can try myself? Thx.

**Comment by thomascenni** [comment]
Hello,
I am using PHP 7.2.21 and Cecil 5.31.4 on MacOSX 10.12.6.
Starting from scratch with the following script is working, may be is something related to the browser cache ?

https://gist.github.com/thomascenni/0e3cbb8273339140bd37b8692441dc91

Thanks
