### ISSUE TITLE
Generate slug from title.

### ISSUE THREAD

**Issue by thomascenni** [Cecilapp/Cecil#838]
Hi,
By default each page is generated as filename-slugified/index.html, according to the [documentation](https://cecil.app/documentation/content/#built-website-tree).

Is it possible to generate the slug from the page title ?
In this way I can have a list of posts that I can simply name post1.md, post2.md, post3.md, ... but I will still have a "beautiful" URL generated from title.
Thanks.

**Comment by Narno** [comment]
Hello @thomascenni, it's not possible but you can override the default slug (created from the file name) with the `slug` variable in the front matter.

ie:
```yaml
---
title: My title
slug: my-title
---
```

**Comment by thomascenni** [comment]
Thanks, I read in the documentation, I hope it was possible to generate automatically the slug from the title.
