### ISSUE TITLE
Custom variables in front matter 

### ISSUE THREAD

**Issue by haraldgroven** [Cecilapp/Cecil#881]
After adding custom variables, in this case `image: 'path/my_filename.jpg' `, in the front matter, and adding  `{{ page.image }}` to `_default/page.html.twig`, I get the following error  

`In PagesRender.php line 155:                                                                                                                                                                                                      [Cecil\Exception\Exception]                                                                                                                                                                            Template "site:_default/page.html.twig" line 26 (for page "another-page"): Neither the property "image" nor one of the methods "image()", "getimage()"/"isimage()"/"hasimage()" or "__call()" exist and have public access in class "Cecil\Collection\Page\Page".  `

Could the documentation include a section on how to make custom variables in the markdown file's front matter accessible to templates?

**Comment by Narno** [comment]
Hello @haraldgroven, as you can read in the [Page Anatomy](https://cecil.app/documentation/content/#page-anatomy) section of the documentation, the front matter must be a valid YAML:
`image = 'path/my_filename.jpg'` -> `image: '/path/my_filename.jpg'`.

Could you try this? Thanks.

**Comment by haraldgroven** [comment]
Sorry for typo in `image: 'path/my_filename.jpg'` 
I have checked that all markdown content pages are valid YAML according to yamllint. However, after adding `{{ page.image }}` to `_default/page.html.twig` cecil expects every single markdown page to have the `image:` key/value pair, and throws exception even for the 404 page. 


`[Cecil\Exception\Exception]
Template "site:_default/page.html.twig" line 26 (for page "404"): Neither the property "image" nor one of the methods "image()", "getimage()"/"isimage()"/"hasimage()" or "__call()" exist and have public access in class "Cecil\Collection\Page\Page".  `

**Comment by Narno** [comment]
I see: you should add a control in your template.
Something like that:
```twig
{% if page.image is defined %}
<img src="{{ url(page.image) }}" alt="{{ page.title }}" />
{% endif %}
```
